In [1]:
def pythonsum(n):
    summed = []
    for i in range(n):
        a = i ** 2
        b = i ** 3
        summed.append(a + b)
    return summed

In [2]:
pythonsum(10)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]

In [5]:
import numpy
def numpysum(n):
    a = numpy.arange(n) ** 2
    b = numpy.arange(n) ** 3
    return a + b

In [6]:
numpysum(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

In [22]:
import sys
from datetime import datetime

size = 10000000
start = datetime.now()
summed = pythonsum(size)
pythondelta = datetime.now() - start
print("pythonsum() elapsed time", pythondelta.microseconds)

start = datetime.now()
summed = numpysum(size)
numpydelta = datetime.now() - start
print("numpysum() elapsed time", numpydelta.microseconds)

print("{} times faster".format(pythondelta / numpydelta))

pythonsum() elapsed time 217684


/usr/local/lib/python3.5/site-packages/ipykernel/__main__.py:4: RuntimeWarning: invalid value encountered in power


numpysum() elapsed time 921989
11.082218985259043 times faster


## NumPy Fundamentals

In [24]:
import numpy as np
list_of_nums = np.array([1, 2, 3, 4, 5])
print(list_of_nums)

[1 2 3 4 5]


In [25]:
type(list_of_nums)

numpy.ndarray

In [27]:
list_of_nums[0]

1

In [28]:
matrix_of_nums = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])
print(matrix_of_nums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order=None, subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an
        object whose __array__ method returns an array, or any
        (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then
        the type will be determined as the minimum type required
        to hold the objects in the sequence.  This argument can only
        be used to 'upcast' the array.  For downcasting, use the
        .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy
        will only be made if __array__ returns a copy, if obj is a
        nested sequence, or if a copy is needed to satisfy any of the other
        requirements (`dtype`, `order`, etc.).

In [30]:
dir(matrix_of_nums)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__r

In [31]:
list_of_nums ** 2

array([ 1,  4,  9, 16, 25])

In [32]:
list_of_nums

array([1, 2, 3, 4, 5])

In [33]:
list_of_nums *= 2

In [34]:
list_of_nums

array([ 2,  4,  6,  8, 10])

In [35]:
list_of_nums *= 2

In [36]:
list_of_nums

array([ 4,  8, 12, 16, 20])

In [37]:
list_of_nums ** 2

array([ 16,  64, 144, 256, 400])

In [38]:
list_of_nums

array([ 4,  8, 12, 16, 20])

In [39]:
list_of_nums + 10

array([14, 18, 22, 26, 30])

In [40]:
list_of_nums

array([ 4,  8, 12, 16, 20])

In [41]:
list_of_nums += 10

In [42]:
list_of_nums

array([14, 18, 22, 26, 30])

In [43]:
matrix_of_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
matrix_of_nums + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [45]:
matrix_of_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
[1, 2, 3, 4, 5] + [1, 2, 3, 4, 5]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [47]:
np.array([1, 2, 3, 4, 5]) + np.array([1, 2, 3, 4, 5])

array([ 2,  4,  6,  8, 10])

In [48]:
matrix_of_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
matrix_of_nums.shape

(3, 3)

In [50]:
other_matrix = np.array([[10, 11, 12, 13],
                       [14, 15, 16, 17],
                       [18, 19, 20, 21]])

In [51]:
other_matrix.shape

(3, 4)

In [52]:
other_matrix + matrix_of_nums

ValueError: operands could not be broadcast together with shapes (3,4) (3,3) 

In [53]:
matrix_of_nums + list_of_nums

ValueError: operands could not be broadcast together with shapes (3,3) (5,) 

In [54]:
big_matrix = np.array([[5, 6, 7],
                      [7, 8, 9],
                      [10, 11, 12],
                      [13, 14, 15],
                      [16, 17, 18],
                      [19, 20, 21]])

In [58]:
big_matrix + list_of_nums

array([[ 6,  8, 10],
       [ 8, 10, 12],
       [11, 13, 15],
       [14, 16, 18],
       [17, 19, 21],
       [20, 22, 24]])

In [56]:
list_of_nums

array([14, 18, 22, 26, 30])

In [66]:
list_of_nums = np.array([1, 2, 3])

In [59]:
matrix_of_nums

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
print(matrix_of_nums.size)

9


In [61]:
matrix_of_nums.shape

(3, 3)

In [64]:
matrix_of_nums.ndim

2

In [67]:
list_of_nums.ndim

1

In [68]:
matrix_of_nums.dtype

dtype('int64')

In [69]:
another_matrix = np.array([[1.0, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

In [70]:
another_matrix.dtype

dtype('float64')

In [71]:
another_matrix

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [72]:
another_matrix *= 1.5

In [73]:
another_matrix

array([[  1.5,   3. ,   4.5],
       [  6. ,   7.5,   9. ],
       [ 10.5,  12. ,  13.5]])

In [74]:
test_matrix = np.array([[1, 2, 3], [4,5,6]])

test_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
test_matrix = np.array([[1, 2, 3], [4,5,6]])
test_matrix.resize((3, 5))

In [79]:
test_matrix

array([[1, 2, 3, 4, 5],
       [6, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [80]:
test_matrix.ndim

2

In [83]:
test_matrix[1][0]

6

In [86]:
print(test_matrix.max(axis=0))

[6 2 3 4 5]


In [87]:
nums = np.random.randint(100, size=(3, 5))

In [88]:
nums

array([[11, 31, 19, 30, 68],
       [39, 21, 48, 57, 41],
       [69, 81, 25, 70, 76]])

In [89]:
print(nums.cumsum(axis=0))

[[ 11  31  19  30  68]
 [ 50  52  67  87 109]
 [119 133  92 157 185]]


In [90]:
print(nums.cumsum(axis=1))

[[ 11  42  61  91 159]
 [ 39  60 108 165 206]
 [ 69 150 175 245 321]]


In [91]:
big_data = np.random.randint(1, 1000, (1000, 100))

big_data

array([[769, 720, 205, ..., 755, 574, 311],
       [438, 751, 702, ..., 825, 672, 340],
       [ 45,  76, 447, ..., 986, 687, 297],
       ..., 
       [420, 588, 556, ..., 577, 771, 179],
       [633, 616, 215, ..., 919, 613, 945],
       [178, 785, 654, ..., 788, 624, 673]])

In [92]:
big_data.shape

(1000, 100)

In [93]:
np.histogram(big_data, bins=5)

(array([19984, 20163, 20132, 19928, 19793]),
 array([   1. ,  200.6,  400.2,  599.8,  799.4,  999. ]))

In [95]:
[x ** 2 for x in big_data.mean(axis=0)]

[235175.53260100001,
 235502.501796,
 251338.78756899998,
 245544.03457600001,
 248950.104601,
 215405.51792399999,
 252601.73402500004,
 250619.38316100003,
 240223.49587599997,
 265959.89836899994,
 261091.36284099999,
 261243.6544,
 244493.65836900001,
 251870.48568900002,
 243157.47210000001,
 244429.38240400003,
 246713.87020899999,
 237154.39022500001,
 264653.65802500007,
 246043.77678400002,
 250035.00122500001,
 259023.99513600001,
 239334.25152400002,
 231385.05062499997,
 256254.638656,
 234792.57891599997,
 245819.62320400003,
 262573.23156099999,
 248262.03108100002,
 240840.47002499999,
 261578.03380900002,
 252035.12496099999,
 250629.39564100001,
 243595.55091599998,
 239147.40672899998,
 238600.01008899999,
 264495.23268100008,
 242033.496961,
 260958.52728100002,
 249696.09241600003,
 237870.79840000003,
 252288.21208900001,
 251772.129361,
 256952.67902499996,
 238817.9161,
 251393.937664,
 263543.62322499999,
 238480.83902500002,
 239406.66126399997,
 243992.5299360